<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="bunit" Version="2.11.3" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="HtmlSanitizer" Version="9.2.1039" />
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="10.0.101" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebView" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.12" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.101" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>
